apiVersion: v1
kind: Service

metadata:
  name: cafeapp-service
  namespace: production

spec:
  selector:
    app: cafeapp

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080

  type: NodePort